### ISSUE TITLE
请问这个怎么用？

### ISSUE THREAD

**Issue by Crazy-Steven** [kevll/DingTalkHelper#1]

**Comment by kevll** [comment]
进入钉钉设置—钉钉小助手，设置好保存后再进考勤打卡界面就生效了。

**Comment by Crazy-Steven** [comment]
installation.cpp:51 APIInternalError
提示这个错误，之前还提示过一次AppleWatch 的错误。

**Comment by kevll** [comment]
请重新下载我Github百度云ipa试一下。

**Comment by Crazy-Steven** [comment]
installation.cpp:42
The WatchKit 2.0 app being installed contains an invalid application executable.

这个问题又出来了，我的系统是11.0.2，需要升级么？

**Comment by Crazy-Steven** [comment]
然后再试就又和以前一样是：
installation.cpp:51 APIInternalError。

**Comment by kevll** [comment]
重新下载的ipa吗?

**Comment by Crazy-Steven** [comment]
是的，但看上去是一样的ipa包，没啥变化啊。

**Comment by Crazy-Steven** [comment]
我是删了重下的，所以一定不会混。

**Comment by kevll** [comment]
百度网盘链接变了哦，你看一下下载下来是不是93.1MB
另外impactor在有些机型上是装不成功的，如果你身边有mac和开发者账号可以选择自签名或者使用[resign](https://github.com/kevll/resign)签名脚本重签名后就可以直接用助手装了

**Comment by Crazy-Steven** [comment]
好的，我再试试。

**Comment by Crazy-Steven** [comment]
下载下来是93.3M啊~

**Comment by Crazy-Steven** [comment]
密码: 83en 的这个么?

**Comment by kevll** [comment]
是的

**Comment by Crazy-Steven** [comment]
成功了，谢谢。
