### ISSUE TITLE
越狱安装插件和没越狱安装ipa都要闪退呢

### ISSUE THREAD

**Issue by wangerwazi** [kevll/DingTalkHelper#10]
安装了越狱版和插件都要闪退，系统是ios10.2的，进入打卡界面都要闪退

**Comment by kevll** [comment]
麻烦贴上崩溃日志，方便分析一下

**Comment by wangerwazi** [comment]
请问奔溃日志在哪里看

**Comment by kevll** [comment]
/private/var/mobile/Library/Logs/CrashRepoter
你可以直接用itools或者其它助手直接查看日志的
另外如果你是Mac系统并且装有Xcode也可用Xcode的device去直接查看

**Comment by wangerwazi** [comment]
奔溃日志找到了，但是我看不懂啊，能否加qq发给你呢？

**Comment by kevll** [comment]
你把Main-Thread的贴到这就行了

**Comment by wangerwazi** [comment]
Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001832bb014 0x18329c000 + 126996
1   libsystem_pthread.dylib       	0x0000000183383450 0x18337e000 + 21584
2   libsystem_c.dylib             	0x000000018322f400 0x1831cc000 + 406528
3   DingTalk                      	0x000000010057872c 0x10008c000 + 5162796
4   DingTalk                      	0x0000000100443224 0x10008c000 + 3895844
5   CoreFoundation                	0x00000001842ed538 0x1841bd000 + 1246520
6   libobjc.A.dylib               	0x0000000182d24838 0x182d1c000 + 34872
7   libc++abi.dylib               	0x0000000182d1366c 0x182cf8000 + 112236
8   libc++abi.dylib               	0x0000000182d12f84 0x182cf8000 + 110468
9   libobjc.A.dylib               	0x0000000182d24690 0x182d1c000 + 34448
10  CoreFoundation                	0x00000001841d0eac 0x1841bd000 + 81580
11  CoreFoundation                	0x00000001841d0d1c 0x1841bd000 + 81180
12  DingTalkHelper.dylib          	0x0000000104c4e02c 0x104c44000 + 41004
13  DingTalk                      	0x0000000102b7e870 0x10008c000 + 45033584
14  DingTalk                      	0x0000000102b73014 0x10008c000 + 44986388
15  DingTalk                      	0x0000000101c15c9c 0x10008c000 + 28875932
16  DingTalk                      	0x00000001004744d0 0x10008c000 + 4097232
17  libdispatch.dylib             	0x00000001831761fc 0x183175000 + 4604
18  libdispatch.dylib             	0x00000001831761bc 0x183175000 + 4540
19  libdispatch.dylib             	0x000000018317ad68 0x183175000 + 23912
20  CoreFoundation                	0x000000018429a810 0x1841bd000 + 907280
21  CoreFoundation                	0x00000001842983fc 0x1841bd000 + 898044
22  CoreFoundation                	0x00000001841c62b8 0x1841bd000 + 37560
23  GraphicsServices              	0x0000000185c7a198 0x185c6e000 + 49560
24  UIKit                         	0x000000018a20d7fc 0x18a193000 + 501756
25  UIKit                         	0x000000018a208534 0x18a193000 + 480564
26  DingTalk                      	0x00000001000910b8 0x10008c000 + 20664
27  libdyld.dylib                 	0x00000001831a95b8 0x1831a5000 + 17848

Main-Thread是这样的，这个是越狱手机安装的ipa版本，我刚才用ios11没越狱的安装了，进入打卡界面也要闪退。

**Comment by zhangdongpo** [comment]
我的进入打卡和签到就crash了

**Comment by kevll** [comment]
@wangerwazi 你贴一下 Last Exception Backtrace

**Comment by wangerwazi** [comment]
Last Exception Backtrace:
(0x1842ed1b8 0x182d2455c 0x1841d0eac 0x1841d0d1c 0x104c4e02c 0x102b7e870 0x102b73014 0x101c15c9c 0x1004744d0 0x1831761fc 0x1831761bc 0x18317ad68 0x18429a810 0x1842983fc 0x1841c62b8 0x185c7a198 0x18a20d7fc 0x18a208534 0x1000910b8 0x1831a95b8)

**Comment by wangerwazi** [comment]
我按照你说的，把定位和和wifi都配置了，不会闪退，但是打卡显示的是外勤。

**Comment by kevll** [comment]
你们主要是Wi-Fi考勤还是定位？
Wi-Fi最准确，定位的话经纬度偏差一点点可能就属于外勤了。
如果是定位考勤，那么请多试几次钉钉小助手里的“开始定位”以此获取新的定位值（前提要在考勤范围内），或者自己百度考勤范围内的经纬度（使用Google定位获得的经纬度），手动输入上去。
如果是Wi-Fi考勤，并且确定macIp无误，那么可能就是钉钉版本的问题了，请下载钉钉4.2.6版本尝试。

**Comment by wangerwazi** [comment]
>  @现在不知怎么回事，又能用了，多谢老大！
