### ISSUE TITLE
手机9.3.3 越狱  安装后提示非官方版本，不能使用。

### ISSUE THREAD

**Issue by 10767637** [kevll/DingTalkHelper#11]
从Pp助手安装最新版4.2.8钉钉，之后从CYDIA市场搜索dingtalkhelp安装0.0.1-19版本，进入钉钉设置，开启助手及定位修改功能，之后使用签到，提示非官方版本，需要人脸识别认证。
看之前的评论说是新版本已解决此问题，请问是我操作有遗漏的原因导致出问题吗？烦请指点一二，谢谢。

**Comment by kevll** [comment]
如果你是越狱手机，直接从App Store下载钉钉，然后再到cydia搜索dingtalkhelp安装，这种方式不存在这种问题。
如果你是非越狱手机，请下载我Github上签名好的ipa进行安装，这个也是测试过的。

**Comment by RoyLaw** [comment]
@kevll 借楼问一下，如果今后dingtalk升级，比如说现在已经是4.2.8，是再次使用您发布的ipa来覆盖当前版本么？还是app内可以直接升级？

**Comment by kevll** [comment]
我发布的ipa和钉钉官方app可以共存的，也就是你手机上可以多开钉钉。升级钉钉只能升级官方钉钉，这个不会被影响。

**Comment by 10767637** [comment]
多开钉钉测试成功，谢谢。
