### ISSUE TITLE
iPhone6 ios10.3.3 钉钉4.2.8 助手0.0.1-19 被检测

### ISSUE THREAD

**Issue by fulingfuling** [kevll/DingTalkHelper#12]
iPhone6 ios10.3.3 已越狱
钉钉4.2.8，通过App Store安装
助手0.0.1-19，通过cydia bigboss源安装
考勤打卡时显示：经安全检查，考勤定位功能正在被模拟定位软件干扰，请卸载模拟定位软件后，重新进行打卡。

**Comment by kevll** [comment]
刚试了越狱手机钉钉4.2.8版本钉钉是可以打卡成功的，你手机上是不是装了其他的模拟定位的插件？
如果确保没有其他模拟定位插件，请尝试下载正版钉钉4.2.6版本尝试。

**Comment by fulingfuling** [comment]
感谢回复！
经再次测试发现，该问题因手机装有其他定位模拟插件造成，无论是否开启插件功能。 @kevll

**Comment by kevll** [comment]
嗯，那我先关闭issue了，有问题再提issue吧

**Comment by weipxiu** [comment]
问题是我一直在用Anywhere用来装逼苹果X，正常时候打卡也没提示这个问题，怎么用咱们这个插件就会有冲突
