### ISSUE TITLE
点击应用中的钉邮图标会产生错误

### ISSUE THREAD

**Issue by RoyLaw** [kevll/DingTalkHelper#17]
自从上个版本开始至目前的V1版，均发现钉邮功能不能使用，从任意入口，包括其它应用列表中点击钉邮的内容会提示内部错误。
![img_7827 20180204-232250](https://user-images.githubusercontent.com/202931/35779104-c57f5efc-0a02-11e8-9b9b-93a7cbae559b.jpg)

**Comment by fly2themoon** [comment]
我也出现了这个问题，我是登录windows钉钉，然后设置了自动转发

**Comment by iOSleep** [comment]
关闭模拟定位后重试看看，估计是hook js和oc通信的时候把别的action处理掉了

**Comment by RoyLaw** [comment]
关闭小助手的开关并点击保存后回到先前的页面仍旧遇到同样的错误。

**Comment by iOSleep** [comment]
越狱方式还是ipa包？

**Comment by RoyLaw** [comment]
未越狱，IPA安装




发自网易邮箱 iPhone 版
在2018年02月08日 15:24，maxu 写道：

越狱方式还是ipa包？
