### ISSUE TITLE
ERROR provision.cpp:81

### ISSUE THREAD

**Issue by YuyangHYY** [kevll/DingTalkHelper#39]
provision.cpp:81
ios/submitDevelopmentCSR =7460
You already have a current iOS Development certificate or a pending certificate request.

![2018-03-29 17 18 57](https://user-images.githubusercontent.com/19391002/38080910-4d7ab0fe-3375-11e8-8f2a-d29255f09c58.png)

**Comment by YuyangHYY** [comment]
我有尝试revoke证书 也是不行，有error出现
[https://www.youtube.com/watch?v=7i-A1ASdu8o](参考)

**Comment by YuyangHYY** [comment]
请问可不可以发一个没有签名的上来 我自己来签名然后安装

**Comment by qianshihua** [comment]
@YuyangHYY 你好，最后解决了吗？

**Comment by qianshihua** [comment]
注册了一个新的appleid可以安装了！！！
