### ISSUE TITLE
provision.cpp:168

### ISSUE THREAD

**Issue by lilovexin** [kevll/DingTalkHelper#6]
Please sign in with an app-specific password. You can create one at appleid.apple.com.

iPhone 6S 没有越狱

**Comment by kevll** [comment]
你的apple账号开启了双重认证。
有两个解决办法：
1.到appleid.apple.com 生成App专用密码，然后使用专用密码
2.重新申请一个新的苹果账号使用

**Comment by lilovexin** [comment]
如果我关闭双重认证是不是就可以了??

**Comment by kevll** [comment]
理论上是这样，你可以试一下

**Comment by lilovexin** [comment]
到appleid.apple.com 哪里可以生成App专用密码??

**Comment by kevll** [comment]
https://support.apple.com/zh-cn/HT204397
