### ISSUE TITLE
需要输入Apple ID 和密码！！！太危险了

### ISSUE THREAD

**Issue by dingjianjaja** [kevll/DingTalkHelper#8]
impactor工具安装IPA，需要输入密码，太危险了，谨慎啊

**Comment by kevll** [comment]
impactor需要输入apple账号密码是因为那个工具使用你提供的账号向Apple申请证书和provsion文件进行签名ipa，然后才能把ipa安装到你的iPhone，不存在什么风险的...
另外你如果担心账号风险，自己从新注册个新的苹果账号不就可以了，几分钟的事...

**Comment by weipxiu** [comment]
这个安卓软件的工具是目前最新越狱公用的工具，不存在什么风险，全球所有越狱者在用的
